# Generated by Django 6.0.3 on 2026-08-30 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=255)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='PHONE', max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=254)),
            ],
            options={
                'db_table': 'POC_CLIENT',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('address', models.CharField(db_column='ADDRESS', max_length=255)),
                ('cleaning_frequency', models.CharField(db_column='CLEANING_FREQUENCY', max_length=255)),
                ('price', models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=10)),
                ('cleaning_instructions', models.TextField(blank=True, db_column='CLEANING_INSTRUCTIONS', null=True)),
                ('client', models.ForeignKey(db_column='CLIENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='client.client')),
            ],
            options={
                'db_table': 'POC_SITE',
            },
        ),
    ]
