# Generated by Django 6.0.3 on 2026-09-09 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_rename_client_site_client_id_siteimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('ONCE', 'ONCE'), ('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY')], db_column='FREQUENCY', default='ONCE', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], db_column='STATUS', default='ACTIVE', max_length=255)),
                ('start_date', models.DateField(db_column='START_DATE')),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('notes', models.TextField(blank=True, db_column='NOTES', null=True)),
                ('created_by', models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.CASCADE, related_name='created_service_schedules', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(db_column='SITE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='client.site')),
            ],
            options={
                'db_table': 'POC_SERVICE_SCHEDULE',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOccurrence',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(db_column='STARTS_AT')),
                ('ends_at', models.DateTimeField(db_column='ENDS_AT')),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], db_column='STATUS', default='SCHEDULED', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, db_column='COMPLETED_AT', null=True)),
                ('completion_notes', models.TextField(blank=True, db_column='COMPLETION_NOTES', null=True)),
                ('schedule', models.ForeignKey(db_column='SCHEDULE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='schedule.serviceschedule')),
            ],
            options={
                'db_table': 'POC_SERVICE_OCCURRENCE',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], db_column='STATUS', default='ASSIGNED', max_length=255)),
                ('contractor', models.ForeignKey(db_column='CONTRACTOR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_occurrences', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(db_column='OCCURRENCE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedule.serviceoccurrence')),
            ],
            options={
                'db_table': 'POC_SCHEDULE_ASSIGNMENT',
                'constraints': [models.UniqueConstraint(fields=('occurrence', 'contractor'), name='unique_occurrence_assignment')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceoccurrence',
            constraint=models.UniqueConstraint(fields=('schedule', 'starts_at'), name='unique_schedule_occurrence'),
        ),
    ]
