# Generated by Django 6.0.3 on 2026-08-25 10:22

import authuser.model.user
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=254)),
                ('is_superuser', models.BooleanField(db_column='IS_SUPERUSER', default=False)),
                ('is_staff', models.BooleanField(db_column='IS_STAFF', default=False)),
                ('is_user', models.BooleanField(db_column='IS_USER', default=True)),
                ('role', models.CharField(choices=[('OWNER', 'OWNER'), ('ADMINISTRATOR', 'ADMINISTRATOR'), ('CONTRACTOR', 'CONTRACTOR')], db_column='ROLE', default=2, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'POC_USER',
            },
            managers=[
                ('objects', authuser.model.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=255)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=255, null=True)),
                ('user', models.OneToOneField(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'POC_USER_DETAIL',
            },
        ),
    ]
