# Generated by Django 6.0.3 on 2026-08-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'ADMINISTRATOR'), ('CONTRACTOR', 'CONTRACTOR')], db_column='ROLE', default='CONTRACTOR', max_length=255),
        ),
    ]
