# Generated by Django 6.0.3 on 2026-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('ADMINISTRATOR', 'ADMINISTRATOR'), ('CONTRACTOR', 'CONTRACTOR')], db_column='ROLE', default='CONTRACTOR', max_length=255),
        ),
    ]
