# Generated by Django 6.0.3 on 2026-08-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(blank=True, db_column='PHONE', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'ADMINISTRATOR'), ('CONTRACTOR', 'CONTRACTOR'), ('OWNER', 'OWNER')], db_column='ROLE', default='CONTRACTOR', max_length=255),
        ),
    ]
