# Generated by Django 6.0.3 on 2026-10-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_contractorinvoice_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvoice',
            name='gst',
            field=models.BooleanField(db_column='GST', default=False),
        ),
        migrations.AddField(
            model_name='contractorinvoice',
            name='gst',
            field=models.BooleanField(db_column='GST', default=False),
        ),
    ]
